version: "3.9"

services:
  backend:
    build:
      context: ./backend/local
    ports:
      - "4000:4000"

  mvc:
    build:
      context: ./apps/mvc
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "4173:4173"
    depends_on:
      - backend

  mvp:
    build:
      context: ./apps/mvp
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "4174:4174"
    depends_on:
      - backend

  mvvm:
    build:
      context: ./apps/mvvm
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "4175:4175"
    depends_on:
      - backend
